name: build

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Load gotip
      run: |
        go install golang.org/dl/gotip@latest
        gotip download

    - name: Build
      run: gotip build -v ./...

    - name: Test
      run: gotip test -v ./...
