name: build

on:
  push:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - name: set up Go
      uses: actions/setup-go@v2.1.5
      with:
        stable: "false"
        go-version: "1.18.0-rc1"

    - uses: actions/checkout@v2.4.0

    - name: Test
      run: go test -v ./...
