name: build

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.18.1"

    - uses: actions/checkout@v2.4.0

    - name: Run test with coverage
      run: go test -coverprofile="coverage.txt" -covermode=atomic ./...
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: coverage.txt

